language: python
python:
  - "3.7"

# Necessary for Python 3.7 support: https://github.com/travis-ci/travis-ci/issues/9815
dist: xenial
sudo: true

install:
  - pip install pipenv
  - pipenv install --dev --three
  - pipenv install -e .
  - pipenv run black --check

script:
  - pipenv run py.test
  - pipenv run flake8 pytch test
