language: python
python:
  - "3.7"

# Necessary for Python 3.7 support: https://github.com/travis-ci/travis-ci/issues/9815
dist: xenial
sudo: true

install:
  - pip install poetry
  - poetry install

script:
  - ./hooks/pre-commit
