language: python
python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev --three
  - pipenv install -e .
  - pipenv run black --check

script:
  - pipenv run py.test
  - pipenv run flake8 pytch test
