language: python
python:
  - "3.7"

# Necessary for Python 3.7 support: https://github.com/travis-ci/travis-ci/issues/9815
dist: xenial
sudo: true

install:
  - pip install poetry
  - poetry install

script:
  - SERIAL=1 ./hooks/pre-commit
  - ./bin/check-for-unbuilt-changes.sh
  - ./bin/check-for-syntax-highlighting-errors.sh
