#!/bin/bash
set -e
pipenv run ./bin/generate_syntax_trees.sh
pipenv run black .
git add pytch/{greencst,redcst}.py
pipenv run flake8 bin pytch test
pipenv run mypy bin pytch test \
    --ignore-missing-imports \
    --follow-imports=silent \
    --strict-optional
pipenv run py.test
