#!/bin/bash
set -e

readonly SOURCE_DIRS=(bin pytch test resources/syntax-highlighting/piro)

run_in_serial() {
    poetry run py.test
    poetry run mypy "${SOURCE_DIRS[@]}"
    poetry run black --check .
    poetry run flake8 "${SOURCE_DIRS[@]}"
}

run_in_parallel() {
    poetry run py.test &
    readonly PYTEST_PID=$!
    poetry run mypy "${SOURCE_DIRS[@]}" &
    readonly MYPY_PID=$!
    poetry run black --check . &
    readonly BLACK_PID=$!
    poetry run flake8 "${SOURCE_DIRS[@]}" &
    readonly FLAKE8_PID=$!

    if ! wait $PYTEST_PID; then
        return 1
    fi
    if ! wait $MYPY_PID; then
        return 1
    fi
    if ! wait $BLACK_PID; then
        return 1
    fi
    if ! wait $FLAKE8_PID; then
        return 1
    fi
}

if [[ "$SERIAL" = 1 ]]; then
    run_in_serial
else
    if ! run_in_parallel >/dev/null 2>&1; then
        tput bold
        tput setaf 1
        echo "Error: pre-commit hook failed. Output below:"
        tput sgr0
        # Show more intelligible output, since running in parallel will
        # interleave it.
        run_in_serial
    fi
fi
