#!/bin/sh
set -e
./bin/generate_syntax_trees.sh
git add pytch/{greencst,redcst}.py
flake8 bin pytch test
mypy bin pytch test \
    --ignore-missing-imports \
    --follow-imports=silent \
    --strict-optional
py.test
